name: CI Workflow

on:
  pull_request:
    branches:
      - main # Only run on the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # Enable npm cache
      
      - name: Install dependencies
        run: npm install
      
      - name: Build the project
        run: npm run build

  unit-tests:
    runs-on: ubuntu-latest
    needs: build # Ensure this job runs after the build job
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'  # This will reuse the cache from the build job 
      
      - name: Run unit tests
        run: npm test # this should be the command to run your unit tests  
